# Generated by Django 4.1.7 on 2023-03-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=10)),
                ('date', models.DateField()),
                ('reason', models.CharField(choices=[('uber', 'uber'), ('grocery stores', 'grocery stores'), ('food', 'food'), ('water can', 'water can'), ('other', 'other')], max_length=20)),
                ('other_reason', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
